### ISSUE TITLE
A issue about NotImplementedError  when runing the code

### ISSUE THREAD

**Issue by HarboDeng** [IntelLabs/MMPano#10]
Owing to the problem of network connection,I choose to download these models involved in  this project to use them directly.But when it happened to the  Mistral-7B-Instruct-v0.2,which is supported according to Readme file, from https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2 , there exist something wrong as follows:

Traceback (most recent call last):
  File "/root/autodl-tmp/MMPano/mm_pano/mmpano.py", line 766, in <module>
    gen_multiviews(**args.__dict__)
  File "/root/autodl-tmp/MMPano/mm_pano/mmpano.py", line 606, in gen_multiviews
    llm_engine = get_llm_engine("/root/autodl-tmp/models/Mistral-7B-Instruct-v0.2", device=device, dtype=dtype, openai_key=api_key)
  File "/root/autodl-tmp/MMPano/mm_pano/utils/llm_engines.py", line 201, in get_llm_engine
    raise NotImplementedError(f"Got unsupported model {model_name}")
NotImplementedError: Got unsupported model /root/autodl-tmp/models/Mistral-7B-Instruct-v0.2

**Comment by ZhipengCai** [comment]
can you provide the way you install the env, and the way you run the code with Mistral? it is indeed already tested on our end, so should be a smooth run with correct setup.

**Comment by HarboDeng** [comment]
I try to load the model used in this project by loading it from local model  downloaded.I change the code in llm_engine.py about some codes judge the modelname.for example
before:
`
def get_llm_engine
elif model_name == "mistralai/Mistral-7B-Instruct-v0.2":
`
after:
`
def get_llm_engine:
    elif model_name == "/root/autodl-tmp/models/Mistral-7B-Instruct-v0.2":
`
