### ISSUE TITLE
Ability to create wrapping 360 images

### ISSUE THREAD

**Issue by hybridherbst** [IntelLabs/MMPano#5]
This is great work! I was wondering if there’s a way to enable the generated images to wrap in Y as well — 360x180, also called equirectangular panoramic, as often used for image-based lighting.

**Comment by ZhipengCai** [comment]
Hey, this is a very good question. It is definitely possible to use similar idea to enable Y direction generation. We tried a few samples in our early experiments. It worked fine for outdoor scenes, but there are currently some inherent bias on the stable diffusion model especially on the indoor scenes. Basically when inpainting the floor and ceiling for some indoor scenes, it can generate artifacted pixels. We did not have time to investigate into this problem further at the current moment.
