### ISSUE TITLE
Regarding the export issue.

### ISSUE THREAD

**Issue by alphazhugit** [IntelLabs/MMPano#7]
I feel exporting HDR panoramas would be more useful.

**Comment by ZhipengCai** [comment]
> I feel exporting HDR panoramas would be more useful.

You mean save it to an .hdr format?

**Comment by alphazhugit** [comment]
> > I feel exporting HDR panoramas would be more useful.
> 
> You mean save it to an .hdr format?

Yes, .exr files are also feasible because HDR panoramic images can be used as light maps, whereas jpg or png are LDR.🙂

**Comment by ZhipengCai** [comment]
Good idea, we will definitely support that later! Thanks for the suggestion!
